FROM pawzar/devops:php-fpm

RUN apt-get -q update && apt-get -qyf --no-install-recommends install \
    openssl libboost-all-dev libssl-dev cmake \
    && apt-get -qy autoremove && apt-get -qy clean all \
    && rm -rf /var/lib/apt/lists/* /var/cache/apk/* /usr/share/doc/*

WORKDIR /opt
RUN git clone https://github.com/adshares/ads.git
WORKDIR /opt/ads/external/ed25519
RUN make -f Makefile.sse2
WORKDIR /opt/ads/build
RUN cmake -DCMAKE_PROJECT_CONFIG=ads ../src/
RUN make -j `nproc` ads install && ads -v

RUN echo "`date`" | tee --append /.image-build-date
