#!/usr/bin/env bash

set -ex

VENDOR_NAME=adshares
PROJECT_NAME=adpay

INSTALLATION_DIR=${INSTALLATION_DIR:-/opt/${VENDOR_NAME}}

GIT_BRANCH_NAME=${GIT_BRANCH_NAME:-master}
GIT_REPO_BASE_URL=${GIT_REPO_BASE_URL:-https://github.com/${VENDOR_NAME}}

cd ${INSTALLATION_DIR}

git clone --depth=1 --single-branch --branch ${GIT_BRANCH_NAME} ${GIT_REPO_BASE_URL}/${PROJECT_NAME}.git \
    || ( cd ${INSTALLATION_DIR}/${PROJECT_NAME} && git fetch && git reset --hard && git checkout ${GIT_BRANCH_NAME} )

#export PYTHONUNBUFFERED=1

cd ${INSTALLATION_DIR}/${PROJECT_NAME}

pipenv install

#screen -S ${PROJECT_NAME} -X quit || true

#ADPAY_MONGO_DB_PORT=27017
#ADPAY_MONGO_DB_NAME=${PROJECT_NAME}
#ADPAY_MONGO_DB_HOST=localhost
#
#ADPAY_SERVER_PORT=8012
#ADPAY_ENABLE_DEBUG_ENDPOINT=0
#ADPAY_SECONDS_PER_HOUR=3600
#
#ADPAY_MAX_USER_KEYWORDS_IN_PROFILE=50
#ADPAY_CALCULATION_METHOD=default
#ADPAY_CALCULATE_TASKS=1
#ADPAY_VALIDATE_CAMPAIGN_FILTERS=1
#ADPAY_HUMAN_SCORE_THRESHOLD=0.0
#
#ADPAY_EVENT_TYPE_CLICK=click
#ADPAY_EVENT_TYPE_VIEW='view
#ADPAY_EVENT_TYPE_CONVERSION=conversion
#
#ADPAY_LOG_CONFIG_JSON_FILE=
#ADPAY_LOG_LEVEL=DEBUG
#
#screen -S ${PROJECT_NAME} -dm bash -c "pipenv run python daemon.py"
