userId={{ $userUuid }}
email={{ $email }}
adserverName={{ config('app.adserver_name') }}
adserverId={{ config('app.adserver_id') }}
publisher=true
websiteUrl={{ $site->url }}
websiteName={{ $site->name }}
category={{ $categories }}
contentLanguage={{ $site->primary_language }}
