<html>
    <head>
        <link href="{{ asset('css/why.css') }}" rel="stylesheet">
    </head>

    <body>
        <div id="container">
            <section id="banner-preview">
                <img src="{{ $url }}" style="max-width: 300px; max-height: 500px;"/>
            </section>
            <section id="supply-info">
                <h3>This ad has been generated by {{ $supplyName }} (<a href="{{ $supplyPanelUrl }}">{{ $supplyPanelUrl }}</a>)</h3>
                <ul>
                    <li>Terms: <a href="{{ $supplyTermsUrl }}">{{ $supplyTermsUrl }}</a></li>
                    <li>Policy: <a href="{{ $supplyPrivacyUrl }}">{{ $supplyPrivacyUrl }}</a></li>
                </ul>
            </section>

            @if ($demand)
            <section id="demand-info">
                <h3>This ad is provided by {{ $demandName  }} (<a href="{{ $demandPanelUrl }}">{{ $demandPanelUrl }})</a></h3>
                <ul>
                    <li>Terms: <a href="{{ $demandTermsUrl }}">{{ $demandTermsUrl }}</a></li>
                    <li>Policy: <a href="{{ $demandPrivacyUrl }}">{{ $demandPrivacyUrl }}</a></li>
                </ul>
            </section>
            @endif
        </div>
    </body>
</html>
