@startuml

class Conversion
{
    +id
    +campaign_id
    +{field} budget_type (in_budget, out_of_budget)
    +{field} type (click, register, buy)
    +link
    +value
    +date
}


class Event
{
    +conversion_id
    +event_type - click,view,conversion
}

class Campaign
{
    +has_convertion
}

@enduml
