easy_admin:
    site_name: 'Classifier - Classify Publisher campaigns'
    disabled_actions: ['delete', 'edit', 'new']
    list:
        max_results: 50
    entities:
        NetworkBanners:
            class: App\Entity\NetworkBanners
            label: 'Banners'
            list:
                title: "List of banners"
                fields:
                    - 'uuid'
                    - { property: 'content', template: '/admin/banners_content.html.twig'}
                    - 'type'
                    - 'width'
                    - 'height'

    design:
        assets:
            css:
                - '/bundles/app/css/admin.css'
            js:
                - '/bundles/app/js/admin.js'
